// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientSave.proto

#ifndef PROTOBUF_ClientSave_2eproto__INCLUDED
#define PROTOBUF_ClientSave_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace jynetwork {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ClientSave_2eproto();
void protobuf_AssignDesc_ClientSave_2eproto();
void protobuf_ShutdownFile_ClientSave_2eproto();

class CSAuthSave;

// ===================================================================

class CSAuthSave : public ::google::protobuf::MessageLite {
 public:
  CSAuthSave();
  virtual ~CSAuthSave();

  CSAuthSave(const CSAuthSave& from);

  inline CSAuthSave& operator=(const CSAuthSave& from) {
    CopyFrom(from);
    return *this;
  }

  static const CSAuthSave& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CSAuthSave* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CSAuthSave* other);

  // implements Message ----------------------------------------------

  CSAuthSave* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CSAuthSave& from);
  void MergeFrom(const CSAuthSave& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 server_id = 1;
  inline bool has_server_id() const;
  inline void clear_server_id();
  static const int kServerIdFieldNumber = 1;
  inline ::google::protobuf::uint32 server_id() const;
  inline void set_server_id(::google::protobuf::uint32 value);

  // optional string udid = 2;
  inline bool has_udid() const;
  inline void clear_udid();
  static const int kUdidFieldNumber = 2;
  inline const ::std::string& udid() const;
  inline void set_udid(const ::std::string& value);
  inline void set_udid(const char* value);
  inline void set_udid(const char* value, size_t size);
  inline ::std::string* mutable_udid();
  inline ::std::string* release_udid();
  inline void set_allocated_udid(::std::string* udid);

  // @@protoc_insertion_point(class_scope:jynetwork.proto.CSAuthSave)
 private:
  inline void set_has_server_id();
  inline void clear_has_server_id();
  inline void set_has_udid();
  inline void clear_has_udid();

  ::std::string* udid_;
  ::google::protobuf::uint32 server_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ClientSave_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ClientSave_2eproto();
  #endif
  friend void protobuf_AssignDesc_ClientSave_2eproto();
  friend void protobuf_ShutdownFile_ClientSave_2eproto();

  void InitAsDefaultInstance();
  static CSAuthSave* default_instance_;
};
// ===================================================================


// ===================================================================

// CSAuthSave

// optional uint32 server_id = 1;
inline bool CSAuthSave::has_server_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSAuthSave::set_has_server_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSAuthSave::clear_has_server_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSAuthSave::clear_server_id() {
  server_id_ = 0u;
  clear_has_server_id();
}
inline ::google::protobuf::uint32 CSAuthSave::server_id() const {
  return server_id_;
}
inline void CSAuthSave::set_server_id(::google::protobuf::uint32 value) {
  set_has_server_id();
  server_id_ = value;
}

// optional string udid = 2;
inline bool CSAuthSave::has_udid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CSAuthSave::set_has_udid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CSAuthSave::clear_has_udid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CSAuthSave::clear_udid() {
  if (udid_ != &::google::protobuf::internal::kEmptyString) {
    udid_->clear();
  }
  clear_has_udid();
}
inline const ::std::string& CSAuthSave::udid() const {
  return *udid_;
}
inline void CSAuthSave::set_udid(const ::std::string& value) {
  set_has_udid();
  if (udid_ == &::google::protobuf::internal::kEmptyString) {
    udid_ = new ::std::string;
  }
  udid_->assign(value);
}
inline void CSAuthSave::set_udid(const char* value) {
  set_has_udid();
  if (udid_ == &::google::protobuf::internal::kEmptyString) {
    udid_ = new ::std::string;
  }
  udid_->assign(value);
}
inline void CSAuthSave::set_udid(const char* value, size_t size) {
  set_has_udid();
  if (udid_ == &::google::protobuf::internal::kEmptyString) {
    udid_ = new ::std::string;
  }
  udid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CSAuthSave::mutable_udid() {
  set_has_udid();
  if (udid_ == &::google::protobuf::internal::kEmptyString) {
    udid_ = new ::std::string;
  }
  return udid_;
}
inline ::std::string* CSAuthSave::release_udid() {
  clear_has_udid();
  if (udid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = udid_;
    udid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CSAuthSave::set_allocated_udid(::std::string* udid) {
  if (udid_ != &::google::protobuf::internal::kEmptyString) {
    delete udid_;
  }
  if (udid) {
    set_has_udid();
    udid_ = udid;
  } else {
    clear_has_udid();
    udid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace jynetwork

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ClientSave_2eproto__INCLUDED
